name: Build Website ZIP
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install and Build
        run: |
          cd client
          npm install
          npm run build
      - name: Upload Build Folder
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: client/dist # Указываем путь к папке dist внутри папки client
